### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [Parrot-Developers/DronesWear#1]
Hey it would be neat to see this app on F-Droid :)

Would it be feasible?

**Comment by djavan-bertrand** [comment]
The app does need the Play Services. I think you can't submit apps that require the PlayServices on F-Droid. Am I right?

Regards, 
Djavan

**Comment by pizzamaker** [comment]
Do you use gradle? You could have a gradle flavor with a play-services substitute

**Comment by djavan-bertrand** [comment]
What do you call substitute?
Without the Play Services the app on the phone can't communicate with the Android Wear device.
Or am I missing something?

**Comment by pizzamaker** [comment]
Please check out http://opengapps.org/

**Comment by djavan-bertrand** [comment]
Sorry I won't have time to do it. But code is open sourced, feel free to port it with opengapps.

Regards,
Djavan
